apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: prod-kafka-jmx
  namespace: prod
  labels:
    release: platform-prometheus
    app.kubernetes.io/name: kafka
spec:
  namespaceSelector:
    matchNames:
      - prod
  selector:
    matchLabels:
      strimzi.io/name: prod-kafka
      scrape: kafka-jmx
  podMetricsEndpoints:
    - port: tcp-prometheus
      path: /metrics
      interval: 30s
      scrapeTimeout: 25s
      scheme: http
      honorLabels: true
      relabelings:
        - sourceLabels: [__meta_kubernetes_pod_name]
          targetLabel: broker
        - sourceLabels: [__meta_kubernetes_namespace]
          targetLabel: namespace
      metricRelabelings:
        - sourceLabels: [__name__]
          regex: "kafka_.*"
          action: keep
